In [1]:
import pandas as pd
import numpy as np
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for i in filenames:
        print(os.path.join(dirname, i))

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
data=pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')

In [3]:
data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [4]:
data.shape

(8693, 14)

In [5]:
data.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [6]:
data.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [7]:
data.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [8]:
features=['HomePlanet', 'CryoSleep', 'Destination', 'Age',
       'VIP', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']

In [9]:
train_data=data.drop('Transported', axis=1)

In [10]:
train_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre

In [11]:
train_data=train_data[features]

In [12]:
train_data=pd.get_dummies(train_data).fillna(0)

In [13]:
train_data

,Age,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,CryoSleep_True,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_False,VIP_True
0,39.0,0.0,0.0,0.0,0.0,False,True,False,True,False,False,False,True,True,False
1,24.0,9.0,25.0,549.0,44.0,True,False,False,True,False,False,False,True,True,False
2,58.0,3576.0,0.0,6715.0,49.0,False,True,False,True,False,False,False,True,False,True
3,33.0,1283.0,371.0,3329.0,193.0,False,True,False,True,False,False,False,True,True,False
4,16.0,70.0,151.0,565.0,2.0,True,False,False,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,41.0,6819.0,0.0,1643.0,74.0,False,True,False,True,False,True,False,False,False,True
8689,18.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,True,False,True,False
8690,26.0,0.0,1872.0,1.0,0.0,True,False,False,True,False,False,False,True,True,False
8691,32.0,1049.0,0.0,353.0,3235.0,False,True,False,True,False,True,False,False,True,False
8692,44.0,4688.0,0.0,0.0,12.0,False,True,False,True,False,False,False,True,True,False

In [14]:
y_train=data['Transported']

In [15]:
y_train

0       False
1        True
2       False
3       False
4        True
        ...
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 8693, dtype: bool

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [17]:
x_train, x_val, y_train, y_val=train_test_split(train_data, y_train, train_size=0.9, test_size=0.1, random_state=1)

In [18]:
x_train.shape

(7823, 15)

In [19]:
x_val.shape

(870, 15)

In [20]:
y_train.shape

(7823,)

In [21]:
y_val.shape

(870,)

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [23]:
d_model=DecisionTreeClassifier(random_state=42)
r_model=RandomForestClassifier(n_estimators=500, max_depth=9, random_state=1)
lr_model=LogisticRegression()

In [24]:
d_model=d_model.fit(x_train,y_train)
r_model=r_model.fit(x_train,y_train)
lr_model=lr_model.fit(x_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [25]:
dpred=d_model.predict(x_val)
rpred=r_model.predict(x_val)
lrpred=lr_model.predict(x_val)

In [26]:
dpred.shape

(870,)

In [27]:
rpred.shape

(870,)

In [28]:
lrpred.shape

(870,)

In [29]:
y_val.shape

(870,)

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
metrics = {
    "Decision Tree": {
        "Accuracy": accuracy_score(y_val, dpred),
        "Precision": precision_score(y_val, dpred, average='weighted'),
        "Recall": recall_score(y_val,dpred, average='weighted'),
        "F1 Score": f1_score(y_val, dpred, average='weighted')
    },
    "Random Forest": {
        "Accuracy": accuracy_score(y_val,rpred),
        "Precision": precision_score(y_val,rpred, average='weighted'),
        "Recall": recall_score(y_val, rpred, average='weighted'),
        "F1 Score": f1_score(y_val, rpred, average='weighted')
    },
    "Logistic Regression": {
        "Accuracy": accuracy_score(y_val, lrpred),
        "Precision": precision_score(y_val,lrpred, average='weighted'),
        "Recall": recall_score(y_val, lrpred, average='weighted'),
        "F1 Score": f1_score(y_val, lrpred, average='weighted')
    }
}

# Print metrics
for classifier, metrics_dict in metrics.items():
    print(f"{classifier} Metrics:")
    for metric, value in metrics_dict.items():
        print(f"{metric}: {value:.4f}")
    print()

Decision Tree Metrics:
Accuracy: 0.7437
Precision: 0.7440
Recall: 0.7437
F1 Score: 0.7436

Random Forest Metrics:
Accuracy: 0.8000
Precision: 0.8006
Recall: 0.8000
F1 Score: 0.7999

Logistic Regression Metrics:
Accuracy: 0.7828
Precision: 0.7859
Recall: 0.7828
F1 Score: 0.7822

In [31]:
test_data=pd.read_csv("/kaggle/input/spaceship-titanic/test.csv")

In [32]:
test_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [33]:
test=test_data[features]

In [34]:
test=pd.get_dummies(test).fillna(0)

In [35]:
test

,Age,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,CryoSleep_True,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_False,VIP_True
0,27.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,True,True,False
1,19.0,9.0,0.0,2823.0,0.0,True,False,False,True,False,False,False,True,True,False
2,31.0,0.0,0.0,0.0,0.0,False,True,False,False,True,True,False,False,True,False
3,38.0,6652.0,0.0,181.0,585.0,False,True,False,True,False,False,False,True,True,False
4,20.0,0.0,635.0,0.0,0.0,True,False,False,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,34.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,True,True,False
4273,42.0,847.0,17.0,10.0,144.0,True,False,False,True,False,False,False,True,True,False
4274,0.0,0.0,0.0,0.0,0.0,False,False,True,False,True,True,False,False,True,False
4275,0.0,2680.0,0.0,0.0,523.0,False,True,False,True,False,False,False,False,True,False
4276,43.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,True,False,True,False

In [36]:
dpredi=d_model.predict(test)
rpredi=r_model.predict(test)
lrpredi=lr_model.predict(test)

In [37]:
dpredi.shape

(4277,)

In [43]:
output=pd.DataFrame({'PassengerId': test_data.PassengerId, 'Transported':dpredi})
output.to_csv("submission-decision.csv",index=False)

In [39]:
rpredi.shape

(4277,)

In [44]:
output2=pd.DataFrame({'PassengerId': test_data.PassengerId, 'Transported':rpredi})
output2.to_csv('submissiony-randomforest.csv',index=False)

In [41]:
lrpredi.shape

(4277,)

In [45]:
output3=pd.DataFrame({'PassengerId': test_data.PassengerId, 'Transported':lrpredi})
output3.to_csv('submissionlogistic.csv',index=False)