In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_csv("Assignment.csv")

In [3]:
data

      Ph      EC     TDS      Cl     Ca    Mg     Na     K   NO3      F
0   6.61   392.0   251.0   128.0   42.0  13.0   76.0   4.0  22.0  0.377
1   6.61   863.0   552.0   340.0  104.0  16.0  122.0  25.0  60.0  0.573
2   7.02   314.0   201.0    64.0   38.0  13.0   47.0   3.0  17.5  0.749
3   6.57   235.0   150.0    50.0   30.0   9.0   15.0   8.0   4.0  0.468
4   7.24   549.0   351.0    96.0   10.0   4.0  189.0   2.0   8.0  2.200
5   7.61   863.0   552.0   113.0   20.0   7.0  340.0   3.0  10.0  2.220
6   7.52  2039.0  1305.0   638.0  244.0  10.0  810.0   4.0   8.0  0.907
7   6.47  2118.0  1355.0  1010.0  339.0   1.0  370.0   4.0  80.0  0.055
8   6.77  1177.0   753.0   110.0  164.0  22.0  252.0   5.0   6.0  0.482
9   7.62   392.0   251.0    53.0   10.0   2.0  161.0   4.0  15.0  2.560
10  8.03   471.0   301.0    50.0    8.0  16.0  142.0   4.0  19.0  2.480
11  7.30   392.0   251.0    89.0   38.0   5.0  118.0   4.0  17.5  1.190
12  6.90   471.0   301.0   124.0   36.0  17.0  102.0   1.0  15.0  1.120
13  7.53   314.0   201.0    43.0   26.0  11.0   63.0   2.0  15.0  1.130
14  7.62   314.0   201.0    74.0   40.0  12.0   49.0   2.0  13.0  0.964
15  6.78   549.0   351.0   266.0   66.0  21.0   95.0   2.0  60.0  0.945
16  6.97   314.0   201.0    89.0   32.0   1.0   46.0   2.0   4.0  0.541
17  7.27   314.0   201.0    64.0   10.0   2.0  119.0   2.0   1.3  4.330
18  6.52   549.0   351.0   227.0   66.0  25.0   82.0   3.0   0.8  0.432
19  7.42   471.0   301.0    96.0   18.0   7.0  129.0   3.0   0.8  1.460
20  7.07   314.0   201.0    42.0   24.0   8.0   66.0   3.0  56.0  1.430
21  7.28   471.0   301.0    46.0   20.0  24.0  145.0   3.0  15.0  2.440
22  6.57   627.0   401.0   287.0   68.0  16.0   49.0   7.0  56.0  0.270
23  7.16   863.0   552.0   467.0   36.0  29.0  312.0   4.0  60.0  2.030
24  7.21   471.0   301.0    89.0   28.0   4.0  139.0   4.0  13.0  1.250
25  7.18   314.0   201.0    85.0   38.0   7.0   61.0   4.0   2.0  0.764
26  6.89   392.0   251.0    74.0   38.0  21.0   43.0   4.0  27.0  0.864
27  6.91   706.0   452.0   227.0   42.0  13.0  169.0   5.0  35.0  0.780
28  7.15   627.0   401.0   252.0   74.0   6.0   85.0  39.0  19.0  0.263
29  6.84   392.0   251.0   156.0   50.0  10.0   92.0   4.0   8.0  0.755
30  6.71   549.0   251.0   308.0  102.0  14.0   94.0  16.0  60.0  0.707
31  7.73   235.0   150.0    89.0   22.0  10.0   89.0   5.0   0.4  0.541
32  6.68   627.0   401.0   234.0  104.0  12.0  107.0   5.0  18.0  0.115
33  7.44   549.0   351.0   110.0   18.0  18.0  191.0   4.0   4.0  1.020
34   NaN     NaN     NaN     NaN    NaN   NaN    NaN   NaN   NaN    NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ph      34 non-null     float64
 1   EC      34 non-null     float64
 2   TDS     34 non-null     float64
 3   Cl      34 non-null     float64
 4   Ca      34 non-null     float64
 5   Mg      34 non-null     float64
 6   Na      34 non-null     float64
 7   K       34 non-null     float64
 8   NO3     34 non-null     float64
 9   F       34 non-null     float64
dtypes: float64(10)
memory usage: 2.9 KB

In [5]:
data.describe()

,Ph,EC,TDS,Cl,Ca,Mg,Na,K,NO3,F
count,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
mean,7.094118,595.235294,377.823529,182.058824,58.970588,11.941176,146.147059,5.705882,22.067647,1.129765
std,0.401264,429.223546,275.514887,197.429226,68.802962,7.277783,144.507341,7.342402,22.178528,0.899371
min,6.470000,235.000000,150.000000,42.000000,8.000000,1.000000,15.000000,1.000000,0.400000,0.055000
25%,6.772500,333.500000,213.500000,74.000000,22.500000,7.000000,68.500000,3.000000,6.500000,0.541000
50%,7.110000,471.000000,301.000000,103.000000,38.000000,11.500000,104.500000,4.000000,15.000000,0.885500
75%,7.390000,627.000000,401.000000,232.250000,66.000000,16.000000,157.000000,4.750000,25.750000,1.385000
max,8.030000,2118.000000,1355.000000,1010.000000,339.000000,29.000000,810.000000,39.000000,80.000000,4.330000

In [6]:
data.columns

Index(['Ph', 'EC', 'TDS', 'Cl', 'Ca', 'Mg', 'Na', 'K', 'NO3', 'F'], dtype='object')

In [7]:
traindata=data.drop(['NO3','F'], axis=1)

In [8]:
traindata

      Ph      EC     TDS      Cl     Ca    Mg     Na     K
0   6.61   392.0   251.0   128.0   42.0  13.0   76.0   4.0
1   6.61   863.0   552.0   340.0  104.0  16.0  122.0  25.0
2   7.02   314.0   201.0    64.0   38.0  13.0   47.0   3.0
3   6.57   235.0   150.0    50.0   30.0   9.0   15.0   8.0
4   7.24   549.0   351.0    96.0   10.0   4.0  189.0   2.0
5   7.61   863.0   552.0   113.0   20.0   7.0  340.0   3.0
6   7.52  2039.0  1305.0   638.0  244.0  10.0  810.0   4.0
7   6.47  2118.0  1355.0  1010.0  339.0   1.0  370.0   4.0
8   6.77  1177.0   753.0   110.0  164.0  22.0  252.0   5.0
9   7.62   392.0   251.0    53.0   10.0   2.0  161.0   4.0
10  8.03   471.0   301.0    50.0    8.0  16.0  142.0   4.0
11  7.30   392.0   251.0    89.0   38.0   5.0  118.0   4.0
12  6.90   471.0   301.0   124.0   36.0  17.0  102.0   1.0
13  7.53   314.0   201.0    43.0   26.0  11.0   63.0   2.0
14  7.62   314.0   201.0    74.0   40.0  12.0   49.0   2.0
15  6.78   549.0   351.0   266.0   66.0  21.0   95.0   2.0
16  6.97   314.0   201.0    89.0   32.0   1.0   46.0   2.0
17  7.27   314.0   201.0    64.0   10.0   2.0  119.0   2.0
18  6.52   549.0   351.0   227.0   66.0  25.0   82.0   3.0
19  7.42   471.0   301.0    96.0   18.0   7.0  129.0   3.0
20  7.07   314.0   201.0    42.0   24.0   8.0   66.0   3.0
21  7.28   471.0   301.0    46.0   20.0  24.0  145.0   3.0
22  6.57   627.0   401.0   287.0   68.0  16.0   49.0   7.0
23  7.16   863.0   552.0   467.0   36.0  29.0  312.0   4.0
24  7.21   471.0   301.0    89.0   28.0   4.0  139.0   4.0
25  7.18   314.0   201.0    85.0   38.0   7.0   61.0   4.0
26  6.89   392.0   251.0    74.0   38.0  21.0   43.0   4.0
27  6.91   706.0   452.0   227.0   42.0  13.0  169.0   5.0
28  7.15   627.0   401.0   252.0   74.0   6.0   85.0  39.0
29  6.84   392.0   251.0   156.0   50.0  10.0   92.0   4.0
30  6.71   549.0   251.0   308.0  102.0  14.0   94.0  16.0
31  7.73   235.0   150.0    89.0   22.0  10.0   89.0   5.0
32  6.68   627.0   401.0   234.0  104.0  12.0  107.0   5.0
33  7.44   549.0   351.0   110.0   18.0  18.0  191.0   4.0
34   NaN     NaN     NaN     NaN    NaN   NaN    NaN   NaN

In [9]:
traindata.isnull().sum()

Ph     1
EC     1
TDS    1
Cl     1
Ca     1
Mg     1
Na     1
K      1
dtype: int64

In [10]:
traindata=traindata.dropna()

In [12]:
targetdata=data[['NO3','F']]

In [13]:
targetdata=targetdata.dropna()

In [18]:
xtrain, xtest, ytrain, ytest=train_test_split(traindata, targetdata, test_size=0.2, random_state=1)

In [19]:
print(xtrain.shape, ytrain.shape, xtest.shape, ytest.shape)

(27, 8) (27, 2) (7, 8) (7, 2)

In [22]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

In [23]:
model.fit(xtrain, ytrain)

RandomForestRegressor(random_state=42)

In [24]:
res=model.predict(xtest)

In [25]:
res

array([[12.567  ,  1.10229],
       [11.407  ,  1.64101],
       [13.535  ,  0.95124],
       [16.954  ,  1.01484],
       [19.551  ,  0.70857],
       [13.97   ,  1.01024],
       [10.474  ,  1.45591]])

In [28]:
result = pd.DataFrame(res)

In [29]:
result

        0        1
0  12.567  1.10229
1  11.407  1.64101
2  13.535  0.95124
3  16.954  1.01484
4  19.551  0.70857
5  13.970  1.01024
6  10.474  1.45591

In [30]:
mse=mean_squared_error(ytest, res)

In [31]:
mse

198.19917130557144